### ISSUE TITLE
Not getting audible alerts

### ISSUE THREAD

**Issue by blindchief1** [robbraxman/braxme#3]
I'm not receiving audible alerts when people I follow post messages or go LIVE on BRAX.  I've tried going to "Account Settings" and check the "Sound" box and save the changes.  However, the change is never saved for me.  This occurs on the @bobby and @bjlinde accounts.

**Comment by robbraxman** [comment]
This is Android? Note the device here.

**Comment by blindchief1** [comment]
This occurs on Apple products, iPhone and iPad. Also occurs on PC using Windows 10.   Just recently I was able to Save the Sound choices in both my @bobby and @bjlinde accounts.
