### ISSUE TITLE
invalid ssl cert

### ISSUE THREAD

**Issue by ChillerDragon** [robbraxman/braxme#4]
https://opensource.brax.me/ threw a warning for me

**Comment by Bot187** [comment]
What kind?

**Comment by ChillerDragon** [comment]
@Bot187 you know the classical warning https://support.mozilla.org/en-US/kb/secure-connection-failed-firefox-did-not-connect

Warning: Potential Security Risk Ahead

**Comment by robbraxman** [comment]
I shut down the server to reduce cost since no one was going to it. The main brax.me site is up
