### ISSUE TITLE
status.php xss bug

### ISSUE THREAD

**Issue by ghost** [robbraxman/braxme#7]
there is a weird thing on status.php, i'm not the one who found it. for example, you could go to
`https://brax.me/prod/status.php?a=<script>alert('hello');document.body.innerText = "world"</script>`
and it would run the javascript without a care.

**Comment by nicolasfritzges** [comment]
it truly is a xss.
payload used: https://brax.me/prod/status.php?a=%3Cscript%3Ealert(document.domain.concat(%22%5Cn%22).concat(window.origin))%3C/script%3E
![2021-09-11 18 49 59 brax me f8d5320284f4](https://user-images.githubusercontent.com/27820946/132962390-72710bf4-21d0-42ad-ada9-a6566d74d93e.png)

**Comment by robbraxman** [comment]
Thank you. It was a test file. It is not used. It has been deleted. Appreciated!

**Comment by robbraxman** [comment]
File deleted
